### ISSUE TITLE
error for finetuning project when running "run.sh"

### ISSUE THREAD

**Issue by brisker** [burness/tensorflow-101#6]
https://github.com/burness/tensorflow-101/tree/master/finetuning
Traceback (most recent call last):
  File "../train_image_classifier.py", line 591, in <module>
    tf.app.run()
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "../train_image_classifier.py", line 443, in main
    train_image_size)
  File "/home/jcc/tensorflow/tensorflow-101/finetuning/preprocessing/preprocessing_factory.py", line 62, in preprocessing_fn
    **kwargs)
  File "/home/jcc/tensorflow/tensorflow-101/finetuning/preprocessing/inception_preprocessing.py", line 308, in preprocess_image
    return preprocess_for_train(image, height, width, bbox, fast_mode)
  File "/home/jcc/tensorflow/tensorflow-101/finetuning/preprocessing/inception_preprocessing.py", line 198, in preprocess_for_train
    tf.image_summary('image_with_bounding_boxes', image_with_box)
AttributeError: 'module' object has no attribute 'image_summary'
My tensorflow is 1.0-rc2 version. Need any change of the code?

**Comment by burness** [comment]
yes @brisker  In Tensorflow 1.0 the tf.image_summary become tf.summay.image, you can change it by a python script in [tensorflow 0.n to 1.0](https://www.tensorflow.org/install/migration)

**Comment by burness** [comment]
@brisker  if you change and run successful  pls make a PR! I am too busy now! Thanks

**Comment by brisker** [comment]
@burness 
I used this script, but unfortunately, still an error occurs:
jcc@jcc:~/tensorflow/tensorflow-101/finetuning_v1.0-rc2/run_scripts$ sh run.sh
fisher
WARNING:tensorflow:From ../train_image_classifier.py:472: softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.
Traceback (most recent call last):
  File "../train_image_classifier.py", line 591, in <module>
    tf.app.run()
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "../train_image_classifier.py", line 484, in main
    [batch_queue])
  File "/home/jcc/tensorflow/tensorflow-101/finetuning_v1.0-rc2/deployment/model_deploy.py", line 202, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "../train_image_classifier.py", line 472, in clone_fn
    scope='aux_loss')
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 118, in new_func
    return func(*args, **kwargs)
TypeError: softmax_cross_entropy() got an unexpected keyword argument 'weight'

**Comment by brisker** [comment]
@burness 
I run the scriot, but unfortunately, still an error occurs:
jcc@jcc:~/tensorflow/tensorflow-101/finetuning_v1.0-rc2/run_scripts$ sh run.sh
Traceback (most recent call last):
  File "./train_image_classifier.py", line 25, in <module>
    from deployment import model_deploy
ImportError: No module named deployment
jcc@jcc:~/tensorflow/tensorflow-101/finetuning_v1.0-rc2/run_scripts$ sh run.sh
fisher
WARNING:tensorflow:From ../train_image_classifier.py:472: softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.
Traceback (most recent call last):
  File "../train_image_classifier.py", line 591, in <module>
    tf.app.run()
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "../train_image_classifier.py", line 484, in main
    [batch_queue])
  File "/home/jcc/tensorflow/tensorflow-101/finetuning_v1.0-rc2/deployment/model_deploy.py", line 202, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "../train_image_classifier.py", line 472, in clone_fn
    scope='aux_loss')
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 118, in new_func
    return func(*args, **kwargs)
TypeError: softmax_cross_entropy() got an unexpected keyword argument 'weight'

**Comment by burness** [comment]
@brisker the TensorFlow 1.0.0 is coming out, Could you update the code first and I have update the code, Could you run again. If the error happens again, try to replace the `slim.losses.softmax_cross_entropy` to `tf.losses.softmax_cross_entropy`.

**Comment by brisker** [comment]
@burness 
still error after I update to tensorflow1.0.0-rc2 and replace the slim.losses.softmax_cross_entropy to tf.losses.softmax_cross_entropy:
jcc@jcc:~/tensorflow/tensorflow-101/finetuning/run_scripts$ sh run.sh
fisher
Traceback (most recent call last):
  File "../train_image_classifier.py", line 591, in <module>
    tf.app.run()
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "../train_image_classifier.py", line 484, in main
    [batch_queue])
  File "/home/jcc/tensorflow/tensorflow-101/finetuning/deployment/model_deploy.py", line 202, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "../train_image_classifier.py", line 472, in clone_fn
    scope='aux_loss')
TypeError: softmax_cross_entropy() got an unexpected keyword argument 'weight'

**Comment by burness** [comment]
@brisker Could you update the tensorflow to TensorFlow 1.0.0 not the rc2.
![image](https://cloud.githubusercontent.com/assets/3112825/23203014/a7c12326-f91b-11e6-8dab-9bfdf670e865.png)
It seems that the code softmax_cross_entropy() `https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/losses/python/losses/loss_ops.py#L354` shouldn't get the error with `weight`. Anywhere, I will reproduce it later.
